
name: Build

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - run: bun build --compile --minify --sourcemap  ./src/index.ts --outfile mg

      - uses: actions/upload-artifact@v4
        with:
          name: mg
          path: ./mg


